name: 🚀 Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: 🚀 Deploy to GitHub Pages
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    concurrency:
      group: "pages"
      cancel-in-progress: false

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🏗️ Build Site
        run: |
          echo "🚀 Building GitHub Pages site..."
          
          # Crear directorio de build limpio
          rm -rf _site
          mkdir -p _site
          
          # Copiar página principal
          if [ -f "github-pages-index.html" ]; then
            cp github-pages-index.html _site/index.html
            echo "✅ Landing page copied"
          else
            echo "❌ Landing page not found"
            exit 1
          fi
          
          # Copiar aplicación completa
          if [ -f "app-github-pages.html" ]; then
            mkdir -p _site/app
            cp app-github-pages.html _site/app/index.html
            echo "✅ App copied"
          else
            echo "❌ App file not found"
            exit 1
          fi
          
          # Copiar recursos estáticos
          if [ -d "src/interfaces/web/static" ]; then
            cp -r src/interfaces/web/static _site/
            echo "✅ Static files copied ($(find _site/static -type f | wc -l) files)"
          else
            echo "❌ Static directory not found"
            exit 1
          fi
          
          # Crear .nojekyll para deshabilitar Jekyll
          touch _site/.nojekyll
          echo "✅ Jekyll processing disabled"
          
          echo "📁 Final site structure:"
          find _site -type f | head -10
          echo "Total files: $(find _site -type f | wc -l)"

      - name: ⚙️ Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: 📤 Upload Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: _site

      - name: 🌐 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4